### PR TITLE
Color palette

### PR DESCRIPTION
**Pull request by Rezmason**
Hey Sea Peoples!

[Colors.](https://www.youtube.com/watch?v=WRCA_Fo0rWA) We've got them, now, in Verreciel, as is demonstrated in the new "scramblePalette" method on the Verreciel object!

The way it works is this: the classic red, cyan, and white colors are in index 0, 1 and 2 of the color palette array. All the colors in the game are now shades of pure red, pure green, or pure blue— but these now stand for percentages of the colors in the palette.

I'm not sure how colors are represented in a HundredRabbits theme, so if this is an awkward API, maybe we can iterate on it. 👌

### CODE REVIEW

**Comment by neauoire** [comment]
Actually, do you think it would be possible to store all colors of the game in one place?
So the themes ecosystem supports 9 colors, 4 foregrounds, 4 background, and 1 background.

I think we could do red, cyan, white, grey as foregrounds, and space colors as the 4 background colors. This is the [theme that will be loaded](https://github.com/hundredrabbits/Themes/blob/master/themes/verreciel.svg) over Verreciel, it's a totaly draft with random colors just to help debug the different parts at.

**Comment by Rezmason** [comment]
Locally it's midnight, and I am at zero stamina, but I'll give this some thought in the morning 😁

**Comment by neauoire** [comment]
Oh! haha no worries, I think I can start with that myself 👍 
Have a good night :) Maybe it'll work in the morning!

**Comment by neauoire** [comment]
Well, that was easy.
Thank you so much for this!! 




it works amazingly.

**Comment by Rezmason** [comment]
You're very welcome 😃

**Pull request merged**
